package gui;

import gui.items.ItemManamgentGui;
import gui.loadingunit.LoadingUnitGui;
import java.util.List;
import javax.swing.JOptionPane;
import models.Customer;
import models.Item;
import models.Stoloc;
import models.User;
import repositories.CustomerRepository;
import repositories.ItemRepository;
import repositories.StolocRepository;
import repositories.UserRepository;

public class DemoApp extends javax.swing.JFrame {

    /**
     * Creates new form Antenna
     */
    public DemoApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnItemRepo = new javax.swing.JButton();
        BtnItemManagement = new javax.swing.JButton();
        BtnOutboundOrderMgmt = new javax.swing.JButton();
        BtnGeneralMgmt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Antenna");

        BtnItemRepo.setText("Generate Stolocs and Items (For Testing)");
        BtnItemRepo.setToolTipText("");
        BtnItemRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnItemRepoActionPerformed(evt);
            }
        });

        BtnItemManagement.setText("Items");
        BtnItemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnItemManagementActionPerformed(evt);
            }
        });

        BtnOutboundOrderMgmt.setText("Outbound Orders");
        BtnOutboundOrderMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOutboundOrderMgmtActionPerformed(evt);
            }
        });

        BtnGeneralMgmt.setText("General Data Management");
        BtnGeneralMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeneralMgmtActionPerformed(evt);
            }
        });

        jButton1.setText("Loading Units");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnItemManagement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOutboundOrderMgmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGeneralMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnItemRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BtnItemRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnItemManagement)
                    .addComponent(BtnOutboundOrderMgmt)
                    .addComponent(BtnGeneralMgmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnItemRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnItemRepoActionPerformed
        //Repo erzeugen
        StolocRepository stolocRepo = new StolocRepository();
        Stoloc stoloc1 = new Stoloc("ABC_123");
        stoloc1.setPickSequence(1);

        Stoloc stoloc2 = new Stoloc("DEF_456");
        stoloc2.setPickSequence(2);

        stolocRepo.addToDatabase(stoloc1);
        stolocRepo.addToDatabase(stoloc2);

        ItemRepository itemRepo = new ItemRepository();

        //2 neue erstellen
        Item myNewItem = new Item("ID001");
        myNewItem.setName("Nike Air");
        myNewItem.setItemLength(100);
        myNewItem.setItemWidth(50);
        myNewItem.setItemHeight(200);
        myNewItem.setPickingStoLoc(stoloc1.getStoLocId());
        itemRepo.addToDatabase(myNewItem);

        Item myNewItem2 = new Item("ID002");
        myNewItem2.setName("Levis Jeans");
        myNewItem2.setItemLength(500);
        myNewItem2.setItemWidth(120);
        myNewItem2.setItemHeight(300);
        myNewItem2.setPickingStoLoc(stoloc2.getStoLocId());
        itemRepo.addToDatabase(myNewItem2);

        //Suchen und verändern
        Item gefundenesItem = itemRepo.getById("ID002");
        gefundenesItem.setItemHeight(gefundenesItem.getItemHeight() + 10);
        itemRepo.updateInDatabase(gefundenesItem);

        //Alle aus DB holen
        List<Item> alleItems = itemRepo.getAll();

        String outputString = "";
        for (Item item : alleItems) {
            outputString += item.toString() + "\n";
        }
        
        
        //Customers und User anlegen: UserRepository userRepository = new UserRepository();
        CustomerRepository customerRepository = new CustomerRepository();
        UserRepository userRepository = new UserRepository();
        // Erstellen und Hinzufügen von drei Benutzern
        User user1 = new User("user001");
        user1.setUserName("Alice");
        userRepository.addToDatabase(user1);

        User user2 = new User("user002");
        user2.setUserName("Bob");
        userRepository.addToDatabase(user2);

        User user3 = new User("user003");
        user3.setUserName("Charlie");
        userRepository.addToDatabase(user3);

        // Erstellen und Hinzufügen von drei Kunden
        Customer customer1 = new Customer("cust001");
        customer1.setAllowedLuType("TypeA");
        customerRepository.addToDatabase(customer1);

        Customer customer2 = new Customer("cust002");
        customer2.setAllowedLuType("TypeB");
        customerRepository.addToDatabase(customer2);

        Customer customer3 = new Customer("cust003");
        customer3.setAllowedLuType("TypeC");
        customerRepository.addToDatabase(customer3);
        

        JOptionPane.showMessageDialog(this, outputString);

    }//GEN-LAST:event_BtnItemRepoActionPerformed

    private void BtnItemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnItemManagementActionPerformed
        // TODO add your handling code here:
        ItemManamgentGui newForm = new ItemManamgentGui();
        newForm.setVisible(true);

    }//GEN-LAST:event_BtnItemManagementActionPerformed

    private void BtnOutboundOrderMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOutboundOrderMgmtActionPerformed
        // TODO add your handling code here:
        OutboundOrderManagementGui newForm = new OutboundOrderManagementGui();
        newForm.setVisible(true);
    }//GEN-LAST:event_BtnOutboundOrderMgmtActionPerformed

    private void BtnGeneralMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeneralMgmtActionPerformed
        // TODO add your handling code here:
        GeneralManagementGui newForm = new GeneralManagementGui();
        newForm.setVisible(true);
    }//GEN-LAST:event_BtnGeneralMgmtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoadingUnitGui newForm = new LoadingUnitGui();
        newForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels = javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx = 0; idx < installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGeneralMgmt;
    private javax.swing.JButton BtnItemManagement;
    private javax.swing.JButton BtnItemRepo;
    private javax.swing.JButton BtnOutboundOrderMgmt;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
