/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.loadingunit;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import repositories.LoadinguntisRepositor;
import models.Loadingunit;
import models.Stoloc;
import repositories.StolocRepository;

/**
 *
 * @author gl //RKU
 */
public class LoadingUnitGui extends javax.swing.JFrame {

    private LoadinguntisRepositor repo =new LoadinguntisRepositor();; 
    private StolocRepository repoStoLoc =new StolocRepository();; 
    /**
     * Creates new form ItemManamgentGui
     */
    public LoadingUnitGui() {
        initComponents();
        
        loadLusFromDB();
        fillComboStoLoc();
        
        
    }
    
    
    private void fillComboStoLoc(){
        cmboStoLoc.removeAllItems();
        List<Stoloc> allStoLocs = repoStoLoc.getAll();
        
        for (Stoloc stoLoc : allStoLocs){
          cmboStoLoc.addItem(stoLoc.getStoLocId());
        }
        
    }
    
    private void loadLusFromDB(){
        List<Loadingunit> allObjs= repo.getAll();
        String[] columnNames = {"luId", "stoLocId", "luType"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Loadingunit lu : allObjs) {
            model.addRow(new Object[]{lu.getLuId(), lu.getStoLocId(), lu.getluType()});
        }        
        luTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        luTable = new javax.swing.JTable();
        textFieldLuId = new javax.swing.JTextField();
        btnAddLu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmboStoLoc = new javax.swing.JComboBox<>();
        cmbLUType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading Units");

        luTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        luTable.setName("luTable"); // NOI18N
        jScrollPane1.setViewportView(luTable);

        textFieldLuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLuIdActionPerformed(evt);
            }
        });

        btnAddLu.setText("Add LU");
        btnAddLu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLuActionPerformed(evt);
            }
        });

        jLabel1.setText("LUId");

        jLabel2.setText("StoLoc");

        jLabel3.setText("LU-Type");

        cmboStoLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmboStoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboStoLocActionPerformed(evt);
            }
        });

        cmbLUType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EP_90", "EP_150", "EP_190" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAddLu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldLuId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmboStoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLUType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cmboStoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLUType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddLu)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLuActionPerformed
       
        Loadingunit lu = new Loadingunit(textFieldLuId.getText());
        lu.setLuType(cmbLUType.getSelectedItem().toString());
        lu.setStoLocId(cmboStoLoc.getSelectedItem().toString());
        repo.addToDatabase(lu);
        loadLusFromDB();
        
    }//GEN-LAST:event_btnAddLuActionPerformed

    private void textFieldLuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLuIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLuIdActionPerformed

    private void cmboStoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboStoLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboStoLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingUnitGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingUnitGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingUnitGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingUnitGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoadingUnitGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLu;
    private javax.swing.JComboBox<String> cmbLUType;
    private javax.swing.JComboBox<String> cmboStoLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable luTable;
    private javax.swing.JTextField textFieldLuId;
    // End of variables declaration//GEN-END:variables
}
