/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author gl
 */

import gui.outboundorder.OutboundOrderGenGui;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.internal.Repository;
import models.OutboundOrder;

import repositories.OutboundOrderRepository;

public class OutboundOrderManagementGui extends javax.swing.JFrame {
    
    /**
     * Creates new form OutboundOrderManagementGui
     */
    private OutboundOrderRepository repository = new OutboundOrderRepository();
    public OutboundOrderManagementGui() {
        initComponents();
        SetUpOBOTable();
    }
    
    private void SetUpOBOTable() {
        List<OutboundOrder> allObjs = repository.getAll();
        String[] columnNames = {"POId", "customerId","state","deliveryTime"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        for (OutboundOrder s : allObjs) {
            model.addRow(new Object[]{s.getPickingOrder(), s.getCustomerId(),s.getState(), s.getDeliveryTime()});
        }
        TblOBO.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblOBO = new javax.swing.JTable();
        BtnGenObo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblOBO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblOBO);

        BtnGenObo.setText("Generate Outbound Order");
        BtnGenObo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenOboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(BtnGenObo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BtnGenObo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGenOboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenOboActionPerformed
        /*
        OutboundOrderRepository OboRepo = new OutboundOrderRepository();
        OutboundOrder Obo1 = new OutboundOrder("1");
        Obo1.setPickingOrder(1);
        Obo1.setState("NEU");
        Obo1.setCustomerId("cust001");
        Obo1.setDeliveryTime(Timestamp.valueOf("2025-08-14 10:30:00"));
        //Obo1.setDeliveryTime(Timestamp.from(Instant.now().plus(100,)));
        OboRepo.addToDatabase(Obo1);
        SetUpOBOTable();
        */
        
        OutboundOrderGenGui newForm = new OutboundOrderGenGui();
        newForm.setVisible(true);
    }//GEN-LAST:event_BtnGenOboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutboundOrderManagementGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutboundOrderManagementGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutboundOrderManagementGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutboundOrderManagementGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutboundOrderManagementGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGenObo;
    private javax.swing.JTable TblOBO;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
